### ISSUE TITLE
Avoid over-calling GetCoreWorker()

### ISSUE THREAD

**Issue by glennmoy** [beacon-biosignals/ray_core_worker_julia_jll.jl#61]
probably makes more sense to have a global worker rather than calling `GetCoreWorker()` over and over again in, e.g., `GetCurrentJobId`, `put` and `get`.

**Comment by kleinschmidt** [comment]
I know I left the original TODO comment, but what's the actual problem here?  The C++/python code does this all over the place and it's not clear to me that we're doing anything wrong here.
